###
GET http://localhost:8080/users/


### 
POST http://localhost:8080/users/
Content-Type: application/json

{
    "username": "Hy",
    "email": "d1at@gmail.com",
    "password": "Oces2023@"
}

###
GET http://localhost:8080/users/6735084a5f2f9a7c4a11b003